version: "3.9"
services:
  wasmd:
    ports:
      - "1317:1317"
      - "26657:26657"
    image: "cosmwasm/wasmd"
    volumes:
      - wasmd_data:/root
    command: /opt/run_wasmd.sh
volumes:
  wasmd_data:
    external: true
