version: "3.9"

services:
  cudos-node:
    container_name: cudos_blast_node
    build:
      dockerfile: cudos-node.dockerfile
      context: ./
      args:
        INIT: 1
    ports:
      - "1317:1317"
      - "26657:26657"
    volumes:
      - cudos_data:/usr/cudos/cudos-data

volumes:
  cudos_data:
