[workspace]
members = ["contracts/*"]

[profile.release]
opt-level = 'z'
strip = true
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true