on: push
name: Code Checks

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repository and checkout branch
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: 16
      - run: npm install
        name: Install root dependencies
      - run: npm run lint
        name: Run a linter check
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repository and checkout branch
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: 16
      - run: cd packages/blast-core && npm install && npm install -g
        name: Install blast-core dependencies and global command
      - run: npm run test test.test.sh
        name: Run e2e tests